name: "Deploy to AWS S3"
description: "Deploy a static website via AWS S3"
inputs:
  bucket:
    description: "The name of the bucket to deploy to"
    required: true
  butcket-region:
    description: "The region of the bucket to deploy to"
    required: false
    default: "us-east-1"
  dist-folder:
    description: "The folder containing the deployable files"
    required: true
runs:
  using: "node16"
  main: "main.js"