name: "Get and cache dependencies"
description: "Get and cache dependencies (via nmp)"
inputs:
  caching:
    description: "Whether to use the cache or not"
    required: false
    default: "true"
outputs:
  used-cache:
    description: "Whether the cache was used or not"
    value: ${{ steps.install-deps.outputs.cache }}
runs:
  using: "composite"
  steps:
    - name: Cache dependencies
      if: ${{ inputs.caching == 'true' }}
      id: cache
      uses: actions/cache@v3
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      id: install-deps
      if: steps.cache.outputs.cache-hit != 'true' || inputs.caching != 'true'
      run: |
        npm ci
        echo "cache='${{inputs.caching}}'"
      shell: bash
